# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='farmacia',
        ),
    ]
