# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nacimiento',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
