# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20160324_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nacimiento',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
